#include "main.h"
#include "gba.h"
#include "title.h"
#include "topbar.h"
#include <stdio.h>
#include <stdlib.h>
#include "game.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/gatechlogo.h"
#include "images/ugasucks.h"
/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

void drawPlayer(Runner *player)
{
  drawRectDMA(player->x, player->y, OBJ_WIDTH, OBJ_WIDTH, BLUE);
}

void movePlayer(Runner *player, int direction)
{
  if (direction == 0)
  {
    player->x += 1 * OBJ_WIDTH;
    if (player->x > BOTTOM_BOUNDARY)
    {
      player->x = BOTTOM_BOUNDARY;
    }
  }
  else if (direction == 1)
  {
    player->y -= 1 * OBJ_WIDTH;
    if (player->y < LEFT_BOUNDARY)
    {
      player->y = LEFT_BOUNDARY;
    }
  }
  else if (direction == 2)
  {
    player->x -= 1 * OBJ_WIDTH;
    if (player->x < TOP_BOUNDARY)
    {
      player->x = TOP_BOUNDARY;
    }
  }
  else if (direction == 3)
  {
    player->y += 1 * OBJ_WIDTH;
    if (player->y > RIGHT_BOUNDARY)
    {
      player->y = RIGHT_BOUNDARY;
    }
  }
}

int handleInput(unsigned int prevButtons, unsigned int currButtons)
{
  if (KEY_JUST_PRESSED(BUTTON_RIGHT, currButtons, prevButtons))
  {
    return 3;
  }
  else if (KEY_JUST_PRESSED(BUTTON_DOWN, currButtons, prevButtons))
  {
    return 0;
  }
  else if (KEY_JUST_PRESSED(BUTTON_LEFT, currButtons, prevButtons))
  {
    return 1;
  }
  else if (KEY_JUST_PRESSED(BUTTON_UP, currButtons, prevButtons))
  {
    return 2;
  }
  return -1;
}

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  Runner player = { 120, 0, 3, 2000 };
  Blocker blocker[25] = {{40, 100}, {50, 120}, {55, 130}, {60, 140}, {65, 135}, {70, 200}, {53, 105}
                        , {60, 110}, {65, 115}, {70, 120}, {75, 125}, {80, 130}, {85, 135}, {90, 140}
                        , {95, 145}, {100, 150}, {105, 155}, {110, 160}, {115, 165}, {120, 170}, {125, 175}
                        , {130, 180}, {135, 185}, {140, 190}, {145, 195}};
  int direction = 0;
  int newDirection;
  int oldx = -1;
  int oldy = -1;
  int firstrun = 1;
  int running = 1;
  char finalscore[10];

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons))
    {
      waitForVBlank();
      state = START;
      player.x = 120;
      player.y = 0;
      player.lives = 3;
      player.score = 2000;
      running = 1;
      firstrun = 1;
    }

    switch (state) {
      case START:
        waitForVBlank();
        drawTitleScreen();
        if (handleTitleTransition(previousButtons, currentButtons))
        {
          fillScreenDMA(BLACK);
          state = PLAY;
          direction = 0;
        }
        break;
      case PLAY:
        newDirection = handleInput(previousButtons, currentButtons);
        if (newDirection != -1)
        {
          direction = newDirection;
          oldx = player.x;
          oldy = player.y;
          movePlayer(&player, direction);
          for (int i = 0; i < 25; i++)
          {
            if (player.x == blocker[i].x && player.y == blocker[i].y)
            {
              player.lives--;
            }
          }
        }
        if (running) {
          player.score--;
          if (player.score == 0)
          {
            state = LOSE;
            running = 0;
          }
        }
        waitForVBlank();
        drawTimer(player.score);
        drawHearts(player.lives);
        drawRectDMA(oldx, oldy, OBJ_WIDTH, OBJ_WIDTH, BLACK);
        drawPlayer(&player);
        if (firstrun)
        {
          for (int i = 0; i < 25; i++)
          {
            drawRectDMA(blocker[i].x, blocker[i].y, OBJ_WIDTH, OBJ_WIDTH, RED);
          }
          firstrun = 0;
        }
        if (player.lives == 0)
        {
          drawFullScreenImageDMA(ugasucks);
          state = LOSE;
          running = 0;
        }
        if (player.y == WIDTH - OBJ_WIDTH)
        {
          waitForVBlank();
          fillScreenDMA(BLACK);
          drawFullScreenImageDMA(gatechlogo);
          state = WIN;
          running = 0;
        }
        break;
      case WIN:
        waitForVBlank();
        sprintf(finalscore, "%d", player.score);
        drawString(30, 50, "You won with a score of: ", RED);
        drawString(50, 50, finalscore, RED);
        break;
      case LOSE:
        drawString(10, 50, "You Lose...", RED);
        break;
    }
    previousButtons = currentButtons; // Store the current state of the buttons
  }
  return 0;
}
